package main

var protoTemplate = `// Code generated by go2proto. DO NOT EDIT.
syntax = "proto3";

{{- range  $v :=  .Imports}}
import "{{$v}}";
{{- end -}}
{{- if .ImportTime}}
import "google/protobuf/timestamp.proto";
{{end}}
package {{.PackageName}};
option go_package = "{{.PackageName}}";
{{ if .Service.Name}}
service {{.Service.Name}} {
    {{- range .Service.ServiceFunctions}}
    {{- if .PingPong}}
    rpc {{.Name}} (stream {{.ParamType}}) returns (stream {{.ResultType}}) {} {{.Comment}}
    {{- else if .Stream}}
    rpc {{.Name}} ({{.ParamType}}) returns (stream {{.ResultType}}) {} {{.Comment}}
    {{- else}}
    rpc {{.Name}} ({{.ParamType}}) returns ({{.ResultType}}) {} {{.Comment}}
    {{- end}}
    {{- end}}
}
{{end -}}
{{range .Messages}}
message {{.Name}} {
    {{- range .MessageFields}}
    {{- if .Doc}} 
    {{.Doc}}
    {{- end}}
    {{.FieldType}} {{.FieldName}} = {{.Index}}; {{.Comment}}
    {{- end}}
}
{{end -}}
`
